name: 'Action for Action for replace version in assemblyinfo file'
description: 'Replace version in assemblyinfo file'
author: 'APS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  filename:
    description: 'AssemblyInfo file path'
    required: true
    default: 'AssemblyInfo.cs'

  keyword:
    description: 'Keyword for search version value in file'
    required: true
    default: 'AssemblyFileVersion'

  new_version:
    description: 'Version for replace'
    required: true
    default: '1.0.0'

runs:
  using: node20
  main: dist/index.js
